sudo: required

language: node_js

node_js:
  - "7"

before_install:
  - docker run -d -p 2181:2181 -p 9092:9092 --env ADVERTISED_HOST=localhost --env ADVERTISED_PORT=9092 --name kafka spotify/kafka
install:
  - npm install -g mocha
  - npm install

services:
  - docker